#!/usr/bin/env python3
"""
run_prioritization.py

Why this exists:
    crown_jewel_scorer.py returns JSON. Humans do not read JSON at 2 a.m. This script
    takes the same inputs and writes a markdown table that a Tier 1 analyst
    can scan from top to bottom. The order of the table is the order they
    should work.

Usage:
    python3 run_prioritization.py \
        --inventory example_asset_inventory.yaml \
        --alerts example_alerts.jsonl \
        --out queue.md
"""

import argparse
import sys
from pathlib import Path

# Pull the scoring logic from the sibling module so we only maintain it once.
sys.path.insert(0, str(Path(__file__).parent))
from crown_jewel_scorer import load_rubric, load_inventory, score_alert  # noqa: E402

import json


PLAYBOOK_BY_TIER = {
    1: "playbooks/tier1-crown-jewels.md",
    2: "playbooks/tier2-high-trust-identity.md",
    3: "playbooks/tier3-build-and-deploy.md",
    4: "playbooks/tier4-saas-data-paths.md",
    5: "playbooks/tier5-lateral-stepping-stones.md",
    6: "playbooks/tier6-noise.md",
}


SLA_BY_TIER = {
    1: "15m MTTD / 2h MTTR",
    2: "15m MTTD / 2h MTTR",
    3: "30m MTTD / 4h MTTR",
    4: "1h MTTD / 8h MTTR",
    5: "1h MTTD / 8h MTTR",
    6: "4h batch / 24h MTTR",
}


def load_alerts_jsonl(path):
    """Load alerts from a JSONL file. One JSON object per line."""
    alerts = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            alerts.append(json.loads(line))
    return alerts


def render_markdown(results):
    """Render the scored, sorted alert list as a markdown table.

    Why markdown:
    Every ticketing system, Slack channel, and Confluence page renders it.
    A Tier 1 can paste this into a ticket and the formatting survives.
    """
    lines = []
    lines.append("# Prioritized Alert Queue")
    lines.append("")
    lines.append("_Generated by crown jewel scorer. Work top to bottom._")
    lines.append("")
    lines.append("| # | Priority | Tier | SLA | Alert | Asset | Severity | Playbook |")
    lines.append("|---|---------:|-----:|-----|-------|-------|----------|----------|")

    for i, r in enumerate(results, start=1):
        playbook = PLAYBOOK_BY_TIER.get(r["tier"], "playbooks/tier6-noise.md")
        sla = SLA_BY_TIER.get(r["tier"], "n/a")
        lines.append(
            f"| {i} | {r['priority_score']} | {r['tier']} | {sla} | "
            f"`{r['detection_name']}` ({r['alert_id']}) | "
            f"{r['asset_name']} (`{r['asset_id']}`) | "
            f"{r['severity']} | [{playbook}]({playbook}) |"
        )

    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- Priority = severity_base * tier_multiplier. Higher is more urgent.")
    lines.append("- Tier is computed from the asset's business impact, data sensitivity,")
    lines.append("  blast radius, and recovery cost. See `code/models/scoring_rubric.yaml`.")
    lines.append("- Any Tier 1 alert gets human eyes within 15 minutes. No exceptions.")
    lines.append("- Tier 6 alerts batch unless they cross an escalation threshold.")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Render a prioritized SOC queue.")
    parser.add_argument("--inventory", required=True)
    parser.add_argument("--alerts", required=True, help="JSONL file.")
    parser.add_argument("--out", default="queue.md")
    args = parser.parse_args()

    rubric = load_rubric()
    inventory = load_inventory(args.inventory)
    alerts = load_alerts_jsonl(args.alerts)

    results = [score_alert(a, inventory, rubric) for a in alerts]
    results.sort(key=lambda r: r["priority_score"], reverse=True)

    md = render_markdown(results)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Wrote {args.out} with {len(results)} alerts.")
    print(f"Top of queue: {results[0]['alert_id']} on {results[0]['asset_name']} "
          f"(tier {results[0]['tier']}, priority {results[0]['priority_score']})")


if __name__ == "__main__":
    main()
